### ISSUE TITLE
Audio Write?

### ISSUE THREAD

**Issue by davidarchi** [CrazyDude1994/android-hw-cam-streaming-rtmp#1]
how we can record audio also?
could you please help ?
Thanks

**Comment by CrazyDude1994** [comment]
@davidarchi I don't support this "library" anymore. You should consider this repository as example if you want to write your own library, not to use this one. Hope this makes sense. Thanks

**Comment by davidarchi** [comment]
Can you help me write to send audio to rtmp server? Actually, i dont have much experience about this part:((. Thank you very much

**Comment by CrazyDude1994** [comment]
@davidarchi me neither. Can't help you with that. Sorry
